swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: <mousikos vivliofagos>

definitions:
  users:
    type: string
    required:
      - id
      - name
      - lastname
      - email
      - password
    properties: 
      id:
        type: integer
        format: int64
      name:
        type: string
  customers:
    type: object
    required:
      - id
      - name
      - phonenumber
      - address
    properties: 
      id:
        type: integer
        format: int64
      name:
        type: string  
      phonenumber:
        type: integer
      address:
        type: string
  newcustomers:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  shops:
    type: string
    required:
      - id
      - address
      - city
     properties: 
      id:
        type: integer
        format: int64
      address:
        type: string 
      city:
        type: string
  admin:
    type: string
    required:
      - id 
    properties:
      id:
        type: string
  products:
    type: string
    required:
      -id
      -title
      -description
      -availability
      -cost
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      availability: string
        type:
      cost: 
        type: integer
  newproducts:
    type: string
    required:
      -id
      -title
      -description
      -availability
      -cost
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      availability: string
        type:
      cost: 
        type: integer
  orders:
    type: object
    required:
      - id
      - userid
      - productid
    properties:
      id:
        type: integer
        format: int64
      userid: 
        type: integer
         $ref: '#/definitions/users'
      productid:
        type: integer
         $ref: '#/definitions/products'
  basket:
    type: object
    required:
      -id
    properties:
      id:
        type: float
    
  
# Describe your paths here
paths:
  
  /customers/products:
    get:
      description: Gets a product
      parameters:
        - name: _sort
          in: query
          required: false
          type: string
        - name: _order
          in: query
          required: false
          type: string
      responses:
        200:
          description: The product succesfully retrieved
          schema:
            type: array
            items:
              $ref: '#/definitions/products'
  /customers: 
    post:
      description: Create a new customer
      operationId: newcustomer
      parameters:
        - name: customer
          in: body
          required: true
          description: Customer to add to the electronic bookstore
          schema:
            $ref: '#/definitions/newCustomers'
      responses:
        201:
          description: Customer created       
  /customers/newproducts: 
    get:
      description:
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: string
          format: double
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/products'
  /customers/orders:
    get:
      description:  The customer gets  orders 
      parameters:
        - in: query
          name: _expand
          description: Expand to customers
          required: false
          type: string
      responses:
        200:
          description: Orders succesfully retrieved
          schema:
            type: array
            items:
              $ref: '#/definitions/orders'
     delete:
      description: The customer deletes an order
      parameters:
        - in: query
          name: _expand
          description: Expand to customers
          required: false
          type: string
      responses:
        200:
          description: Order succesfully deleted
          schema:
            type: array
            items:
              $ref: '#/definitions/orders'
  /shops/products:
    get:
      description: The shops give their products
      parametres:
        -in: query
        required: false
        type: string
      responses: 
        200:
          description: upload the products
          schema:
            $ref: '#definitions/products'
    delete:
      description:  The shops delete their products
      parametres:
        -in: query
        required: false
        type: string
      responses:
        200:
          description: products deleted
          schema:
            type: string
            
